project_id = "vzgrnfoqdhjizttoxnhh"

[functions.meli-auth]
verify_jwt = false

[functions.meli-oauth-callback]
verify_jwt = false

[functions.meli-refresh-token]
verify_jwt = false

[functions.meli-sync]
verify_jwt = false

[functions.meli-listing-actions]
verify_jwt = false

[functions.meli-listing-generator]
verify_jwt = false
